8. Write an Assembly Language Program to compare two strings.(Using MACRO) 
Software required: MASM (Macro Assembler from Microsoft Corp.) 
PRINT MACRO MES ; Macro to display string 
 MOV AH,09H 
 LEA DX, MES
INT 21H 
 ENDM 
.MODEL SMALL 
.DATA 
MS1 DB 10,13,”ENTER FIRST STRING:$” 
MS2 DB 10,13,”ENTER SECOND STRING:$” 
MS3 DB 10,13,”EQUAL STRINGS$” 
MS4 DB 10,13,”UNEQUAL STRINGS$” 
BUFF1 DB 10 DUP(‘$’) 
BUFF2 DB 10 DUP(‘$’) 
.CODE 
MOV AX,@DATA 
MOV DS,AX 
MOV ES,AX 
PRINT MS1 
MOV AH, 0AH 
LEA DX, BUFF1 
INT 21H 
PRINT MS2 
MOV AH, 0AH 
LEA DX, BUFF2 
INT 21H 
MOV CL, LENGTH BUFF1 
MOV CH, LENGTH BUFF2 
CMP CL,CH 
JNE UNEQ 
MOV CH,00H 
LEA SI, BUFF1 
LEA DI, BUFF2 
CLD
REPE CMPSB 
JNZ UNEQ 
PRINT MS3 
JMP FINISH 
UNEQ: PRINT MS4 
FINISH: MOV AH, 4CH 
INT 21H 
END